### ISSUE TITLE
LSR should clear N flag

### ISSUE THREAD

**Issue by johnor** [robinlinden/n_e_s#21]
It seems like the negative status flag should always be cleared when doing a LSR operation: https://www.c64-wiki.com/wiki/LSR

> LSR affects 3 of the CPU's status flags:
> - The negative status flag is always unconditionally cleared.
> - The zero flag is cleared unless the operand is zero
> - The carry flag is copied from the least significant bit (bit 0) of the operand prior to shifting

We do not clear the negative status flag right now:
```c++
        case LSR_A:
            pipeline_.push([=]() {
                set_carry(registers_->a & 1);
                registers_->a &= ~1;
                registers_->a >>= 1;
                set_zero(registers_->a);
            });

```

**Comment by robinlinden** [comment]
You might be right. I looked at
https://www.masswerk.at/6502/6502_instruction_set.html#LSR when
implementing it and that leaves it unaffected. I think it makes more sense
to always clear it. I had a look at a few other sources and at least one
says to clear it if bit 7 isn't set which it will never be. Feel free to
open a PR fixing it.
